name: build

on: [push, pull_request]

env:
  CI: "1"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stuff
        run: sudo apt-get -y install scons

      - name: Build and test
        run: ./test
